[project]
name = "ems_textolytics"
version = "0.0.1"
authors = [
  { name="sdreep", email="textolytics@gmail.com" },
]
description = "EMS Python Services"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/textolytics/nbpy"
Issues = "https://github.com/textolytics/nbpy/issues"